# Generated by Django 3.0.8 on 2020-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('doa', models.CharField(max_length=50)),
                ('dod', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=10)),
                ('type_of_bed', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=150)),
                ('state1', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('doccheck', models.CharField(max_length=150)),
            ],
        ),
    ]
